### ISSUE TITLE
Linux CMake Build failed - Rename fontCache.h at include directory

### ISSUE THREAD

**Issue by sourligas** [mmertama/FigmaQML#1]
i tried to compile from sources the FigmaQML project on Linux but I had a problem with CMake build errors about **fontCache.h** header file. 

It should be renamed to **fontcache.h** on directory **include** since it is being used on some source files with lowercase letters and as well as on CMakeLists.txt file too.

**Comment by mmertama** [comment]
I was supposed to fix this long ago, but done in windows the change was not perceived and thus committed into Github. Strange still this was no issue on my local machine, maybe the pull worked that out silently and as you had a fresh clone this emerged an issue. Still I injected this directly into Gihub and wish it is ok now.
