### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by kodarn** [mmertama/FigmaQML#12]
FigmaQML have helped me a great deal in converting graphical elements to QML. Thank you for your dedication and hard work on FigmaQML. 

Using the attached file, FigmaQML fails with a error message which could be somewhat more helpful. Please let me know if you require any further information or if there is anything else I can do to assist in resolving this issue. I appreciate your attention to this matter and look forward to a resolution.

<img width="339" alt="Screengrab" src="https://github.com/mmertama/FigmaQML/assets/24460172/4baa21ef-8e77-4ee2-af8b-f4654bef5fef">

The Figma-file is attached to this bugreport:

[ContactWindow.fig.gz](https://github.com/mmertama/FigmaQML/files/12093499/ContactWindow.fig.gz)

**Comment by mmertama** [comment]
Looks like service error - please retry. I succeeded just few minutes ago (Mac native build)

**Comment by mmertama** [comment]
Looks like CORS issue (see: https://simplelocalize.io/blog/posts/what-is-cors/) 

Below is the error log captured: - I have no idea how to fix in FigmalQML code. Probably WebAssembly version wont work within too big Figma documents. Please try the native FigmaQML - I havent see such issue there.  

self.moduleConfig.printErr @ qtloader.js:370
qtloader.js:370 Requested MSAA sample count 8 but supported sample counts are QList(1) , using sample count 1 instead
self.moduleConfig.printErr @ qtloader.js:370
FigmaQML.html:1 Access to XMLHttpRequest at 'https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7001d767-f9e2-4656-bde8-6fed726bd164' from origin 'https://mmertama.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
qtloader.js:370 QNetworkAccess: got HTTP status code 0 which is not expected from url: "https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7001d767-f9e2-4656-bde8-6fed726bd164"
self.moduleConfig.printErr @ qtloader.js:370
figma-alpha-api.s3.us-west-2.amazonaws.com/images/7001d767-f9e2-4656-bde8-6fed726bd164:1     Failed to load resource: net::ERR_FAILED
qtloader.js:370 qml: Network error: 399, Not Found
