### ISSUE TITLE
Does not build binary files under Windows.

### ISSUE THREAD

**Issue by Patogenich** [mmertama/FigmaQML#13]
Does not build binary files under Windows.
Hi ! 

I am trying to build a project under Windows. All dependencies are installed.
In the msvc_build.bat file I specified the correct path to my version of QT.
In x64 Native Tools Command Prompt for VS 2019 I run msvc_build.bat, but I get an error when building.

``` 
>cmake .. -DCMAKE_BUILD_TYPE=Release
-- Building for: Ninja
-- The CXX compiler identification is MSVC 19.29.30151.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found WrapVulkanHeaders: C:/Toolchains/msys64/clang64/include
Project is Qt6
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: D:/Personal/Repos/FigmaQML/build

d:\Personal\Repos\FigmaQML\build>msbuild FigmaQML.sln /property:Configuration=Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009:Project file does not exist
Switch: FigmaQML.sln

d:\Personal\Repos\FigmaQML\build>C:\Qt\6.3.2\msvc2019_64\bin\windeployqt --qmldir ../qml Release
"Release" does not exist.
```
What could be the reason ?

**Comment by mmertama** [comment]
I dont have a Windows, but if you do these ba steps manually: 

1. echo Expected to be executed in x64 Native Tools Command Prompt for VS 2019
2. set QT_DIR=C:\Qt\6.3.1\msvc2019_64
3. set CMAKE_PREFIX_PATH=%QT_DIR%\lib\cmake
4. mkdir build
5. pushd build
6. cmake .. -DCMAKE_BUILD_TYPE=Release
7. msbuild FigmaQML.sln /property:Configuration=Release
8. %QT_DIR%\bin\windeployqt --qmldir ../qml Release
9. copy ..\OpenSSL_win\*.dll Release
10. popd
it looks like msbuild does not find the solution file (FigmaQML.sln)  - you may search it, if its not located in D:/Personal/Repos/FigmaQML/build as it says ... Probably it works only in C drive.    The "Switch: FigmaQML.sln" line is pretty fishy as it thinks FigmaQML.sln is a switch (option --- ?) where is is assumed to be a positional parameter. Therefore just manually running "msbuild FigmaQML.sln /property:Configuration=Release" may just work

**Comment by Patogenich** [comment]
After step 6, no FigmaQML.sln file is created in the build directory. 
I moved the project directory to the C:\ drive.
The structure of the build directory looks like this.
```
|---build
|   |---build.ninja
|   |---CMakeCache.txt
|   |---cmake_install.cmake
|   |---.qt
|   |   |---QtDeploySupport.cmake
|   |   `---deploy_qml_imports
|   |       `---FigmaQML.cmake
|   |---.qt_plugins
|   `---CMakeFiles
|       |---clean_additional.cmake
|       |---cmake.check_cache
|       |---CMakeConfigureLog.yaml
|       |---rules.ninja
|       |---TargetDirectories.txt
|       |---3.27.8
|       |   |---CMakeCXXCompiler.cmake
|       |   |---CMakeDetermineCompilerABI_CXX.bin
|       |   |---CMakeRCCompiler.cmake
|       |   |---CMakeSystem.cmake
|       |   `---CompilerIdCXX
|       |       |---CMakeCXXCompilerId.cpp
|       |       |---CMakeCXXCompilerId.exe
|       |       |---CMakeCXXCompilerId.obj
|       |       `---tmp
|       |---CMakeScratch
|       |---FigmaQML.dir
|       |   |---FigmaQML_autogen
|       |   |   `---CCBC4FUR7J
|       |   `---src
|       |---FigmaQML_autogen.dir
|       |   |---AutogenInfo.json
|       |   `---AutoRcc_qml_CCBC4FUR7J_Info.json
|       |---pkgRedirects
|       `---ShowIncludes
|           |---foo.h
|           |---main.c
|           `---main.obj
```

**Comment by mmertama** [comment]
Propably something has changed in windows tooling, after 
_cmake .. -DCMAKE_BUILD_TYPE=Release_
 step you may try 
_cmake --build . --config Release_ 
That would be the much better, but previously not worked with MSVC, but with some luck, its fixed

**Comment by Patogenich** [comment]
I deleted the build directory and did all the steps again, but this time I used the command: _cmake --build . --config Release_.
And again I got the error, only now it's different.
```
c:\FigmaQML\build>cmake --build . --config Release
Error: could not load cache
```

If I first execute _cmake .. -DCMAKE_BUILD_TYPE=Release_ and then _cmake --build . --config Release_, there will be a very large number of errors.

**Comment by mmertama** [comment]
Did you call 'cmake ..' prior to that command? The assumption is that you are in the build folder, created in the project folder. I.e. the folder where the top level CMakeLists.txt is located. Hence 'cmake ..' tells that CMakeLists.txt is one above, once you have called it a CMakeCache.txt has appeared in the folder you are located. Hence 'cmake --build .' finds that file from the current folder and can build the project. build_type and Release makes sure that you are building a release, but you can omit them.  Is cmake .. already  giving any errors? That tells the build environment is unexpected.  Please delete CMakeCache.txt before calling cmake .. - there are cases where that helps.

**Comment by Patogenich** [comment]
It worked !
Thank you very much !
Here is the sequence of steps that led to success.

1. echo Expected to be executed in x64 Native Tools Command Prompt for VS 2019
2. set QT_DIR=C:\Qt\6.3.1\msvc2019_64
3. set CMAKE_PREFIX_PATH=%QT_DIR%\lib\cmake
4. mkdir build
5. pushd build
6. cmake ..
7. cmake --build . --config Release

An executable file FigmaQML.exe is created in the root of the build directory.
The Figma project is imported with artifacts, but this can be corrected manually.

**Comment by mmertama** [comment]
Great to hear! Thank you for digging this out, the sequence will be the great help. I will check the build scripts accordingly once I on Windows, but meanwhile the manual steps you listed would be FAQ :-D

**Comment by Patogenich** [comment]
Glad to help. 
Thank you so much for such a tool.

P.S..
Figma has a plugin QT Bridge for Figma, it unloads the whole project for further loading into QT Design Studio, maybe you should try parsing this file, it seems to me that it has all the ready-made qml in it, but I'm not 100% sure.
