### ISSUE TITLE
Do you have a demonstration tutorial video? It looks very complex to use

### ISSUE THREAD

**Issue by mp437376671** [mmertama/FigmaQML#14]

**Comment by mmertama** [comment]
Sorry, I have videos,  maybe one day...  how do you see it difficult? What kind of issues you have had? Im about to release a new version next week and it would be greatly helpful if you can elaborate more if there is anything I can do in the GUI or documentation. I personally see the flow just 1) Draw UI using Figma, 2) set your personal and project tokens. 3) Fetch data 4) Set view you are interested 5) Download QML ... That is going to be changed a bit next week, far more useful. I also have lot of README updates coming, I hope that helps.
