### ISSUE TITLE
Button changes like color

### ISSUE THREAD

**Issue by QMand** [mmertama/FigmaQML#17]
Good day,

Thank you for this application!

I wanted to find out whether we could add a property to a button for example to be able to 'change' the color when clicked on. In figma I can make a component where the button is not pressed and pressed and they have a different look to them but I'm not sure if it's possible to get it into this program.

I see that I can get the Events when pressing on the button and I can change the text or even the entire 'component'.

In the readme you mention properties like qml?topic_subscribe.text where I can then change the text but I'm not sure what else could be used. (I've used onClicked,text,asLoader)

Thank you!

**Comment by mmertama** [comment]
Hello,

topic_subscribe.color should change the color as .text changes the text
property.

Best Regards

Markus

**Comment by QMand** [comment]
Ahh I see thank you!

This really nice software. 
Thank you for it!

**Comment by mmertama** [comment]
Im not sure if my recommendation worked - please try property_access_imporovements branch, there Im building an improved approach.

**Comment by mmertama** [comment]
3.1 - make this easier - please see qmqtti example

**Comment by QMand** [comment]
Thank you I've been away and I will definitely try this this upcoming weekend. I have tried your recommendation and it does also seem to add the .color and so forth to the qml so it seems to be working. But this weekend I will have a further look.
