### ISSUE TITLE
"COMPONENT_SET" (component variants) unsupported

### ISSUE THREAD

**Issue by kenfred** [mmertama/FigmaQML#2]
When attempting to access a project with component variants, application raises the error:

FigmaParser exception: Non supported object type: "COMPONENT_SET"

App data:
Figma to QML generator, version: 1.0.0, Markus Mertama 2020

**Comment by lin-sein** [comment]
![image](https://user-images.githubusercontent.com/8773112/130893960-0ad7f65a-9a2b-4776-b37c-91cb13b6f00d.png)

**Comment by mmertama** [comment]
Thanks, it looks like Figma has been updated with an element that is not recognized.

**Comment by mmertama** [comment]
I quickly figured out how to make a COMPONENT_SET using Figma, but I made it to be as FRAME as it does according to spec. I hope that solves it.

**Comment by scarrrr316** [comment]
I have this issue too how can i fix it .
my figma project link: https://www.figma.com/file/Q4Bcducycs4K4DoOI6WJQ8/Untitled?node-id=0%3A1
