### ISSUE TITLE
cant use qml file with qtquick

### ISSUE THREAD

**Issue by scarrrr316** [mmertama/FigmaQML#3]
python code :
```
import os
from pathlib import Path
import sys

from PySide2.QtGui import QGuiApplication
from PySide2.QtQml import QQmlApplicationEngine


if __name__ == "__main__":
    app = QGuiApplication(sys.argv)
    engine = QQmlApplicationEngine()
    engine.load(os.fspath(Path(__file__).resolve().parent / "Page_1_figma_Card_figma.qml"))
    if not engine.rootObjects():
        sys.exit(-1)
    sys.exit(app.exec_())

```
it showed nothing after i run this code

how should i fix this problem ,is there any mistake in my code?

data(qml,code,imgae):
[Page_1_figma.zip](https://github.com/mmertama/FigmaQML/files/7375383/Page_1_figma.zip)

**Comment by mmertama** [comment]
Sorry I have only used QML with C++ I cannot comment your code. I opened the QML with qmlscene (Qt's bin folder) and it is able to show the qml file you provided.

**Comment by scarrrr316** [comment]
> Sorry I have only used QML with C++ I cannot comment your code. I opened the QML with qmlscene (Qt's bin folder) and it is able to show the qml file you provided.

can you send me the c++ source code plz

**Comment by mmertama** [comment]
Just use qt creator to create you an QML application, it generates an
"Hello World" C++ app of which QML file you can replace with your own. Add
qml and your images in the resources.
