### ISSUE TITLE
ptoject token 

### ISSUE THREAD

**Issue by AhmedLilah** [mmertama/FigmaQML#4]
the way to get the project token is very unclear. all I got from it is to copy the URL and that didn't work.

**Comment by agray424** [comment]
Yes I did not get this either, but the only part of the url you need is this ...

https://www.figma.com/file/<THIS PART OF THE URL IS YOUR PROJECT TOKEN>/<Your Project title>

**Comment by agray424** [comment]
Yes I found this unclear to, but then I am still having trouble running the Binary file. From what I have found out, your 'Project Token can be found in the URL of your Figma project when opened via the Browser, not sure where to find it in the Desktop version.

https: // www.figma.com / file / **Your 'Project Token' is here** / ...

**Comment by mmertama** [comment]
I elaborated the documentation.  Probably there is no way to find that in the desktop app.
