### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by Nyite** [mmertama/FigmaQML#5]
Hello.
I've entered my tockens as told in README.
After pressing the "Connect" button i'm getting JSON parse errors.

![image](https://user-images.githubusercontent.com/61917981/176843510-49ef9f95-fc33-4365-8e1a-3b4c4fece6a6.png)
![image](https://user-images.githubusercontent.com/61917981/176843671-7ebbd742-8b14-4b6f-b20c-4265ebd7d4b1.png)

Am i missing some intermediate steps?

**Comment by agray424** [comment]
You have got further than me but I think you just need the 'Project Token' part of the URL and not the entire URL?

So in your case the section starting /JvnFLxg ...YeGu/
