### ISSUE TITLE
module "QtGraphicalEffects" is not installed

### ISSUE THREAD

**Issue by Senkai350** [mmertama/FigmaQML#7]
i try to run qml generated by FigmaQML using qt 6.2 in qt creator and get error QQmlApplicationEngine failed to load component
qrc:/Test/main.qml:3:1: module "QtGraphicalEffects" is not installed what i make to do?
main.cpp code
`#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    const QUrl url(u"qrc:/Test/main.qml"_qs);
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}
`
I also attached qml file in qml.zip
[qml.zip](https://github.com/mmertama/FigmaQML/files/9119569/qml.zip)

**Comment by mmertama** [comment]
Hi, you have to install that using the Qt Maintenance Tool. Are you using Qt5 or Qt6? For Qt6 that is part of the Qt5 Compatability module.

**Comment by mmertama** [comment]
Install Qt5 Compatability module.
