### ISSUE TITLE
Component Type

### ISSUE THREAD

**Issue by haknkayaa** [mmertama/FigmaQML#8]
Hello,

First of all, the work is perfect. I've tested it on several projects. I am new to Figma. However, I'm wondering this. Can we identify the components in the Figma by QML what their equivalents are? For example, I want the "Rectangle" component in Figma to be "Window" in a QML. Is there such a feature or any trick?

**Comment by mmertama** [comment]
Hi, It has been under consideration, especially how to draw a "button" that
actually is translated to a button QML component. Maybe some tagging would
do it.  However not now actively developing that.

**Comment by mmertama** [comment]
Next week your request should be answered, stay tuned :-D

**Comment by mmertama** [comment]
In FigmaQML 3.0.0
