### ISSUE TITLE
figma parser exception: unsupported object type 'COMPONENT SET'

### ISSUE THREAD

**Issue by AzlanCoding** [mmertama/FigmaQML#9]
I'm trying to convert my figma project at https://www.figma.com/file/VnN352ZUMh54Okc16r6msl/Robotics-Attendance?node-id=0%3A1 to qml. However, when converting, a pop-up appears saying `figma parser exception: unsupported object type 'COMPONENT SET'`
![image](https://user-images.githubusercontent.com/101229146/199156808-101b0053-4317-4fd5-8a12-2cc9560fd9d4.png)
Are components still supported? If not, is there a workaround for figma components? (i.e. export qml without the figma components)
Any help is appreciated.

**Comment by mmertama** [comment]
It looks like Figma has updated its ok internal representation a bit,
namely bringing new components. Im working with an update and will try if I
gonna get your document working.

**Comment by mmertama** [comment]
Kind of fix at https://github.com/mmertama/FigmaQML/tree/wasm_async, I
hopefully get that to master during this week - but here is a sneak peek

I just made COMPONENT_SET to be as-a frame as they should be pretty same
thing. But probably there are issues. But at least it now generates
something.

Br,
Markus

**Comment by mmertama** [comment]
Fixed in version 2.0.0

**Comment by AzlanCoding** [comment]
Thank you so much!
